name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        source project_configure
        sp_project_build

    - name: Test
      working-directory: ${{github.workspace}}
      run: |
        source project_configure
        sp_project_test
